---
- name: Add base repository for VirtualBox
  yum_repository: name='virtualbox' description='VirtualBox' baseurl='{{virtualbox_url}}' gpgcheck=yes gpgkey=https://www.virtualbox.org/download/oracle_vbox.asc enabled=yes state=present
  when: ansible_os_family == 'RedHat'

- name: Install build dependencies
  yum: name={{item}} state=present
  with_items:
    - gcc
    - make
    - kernel-devel-{{ansible_kernel}}
    - dkms
    # Note: Addint dkms at this step will rebuild the kernel module when installing Vbox in the next step

- name: install Virtualbox package from Virtualbox Repository
  yum: state=present name={{ item }}
  with_items:
    - VirtualBox-5.1

- name: Check if kernel module needs to be rebuilt
  command: VBoxManage list vms
  check_mode: no
  changed_when: '"Please recompile the kernel module" in virtualbox__r_kernel.stdout'
  register: virtualbox__r_kernel

- name: Recompile kernel
  command: /sbin/vboxconfig
  register: last
  when: virtualbox__r_kernel.changed
