---

- name: Add base repository for VirtualBox
  yum_repository: name='virtualbox' description='VirtualBox' baseurl='{{virtual_box_url}}' gpgcheck=yes gpgkey=https://www.virtualbox.org/download/oracle_vbox.asc enabled=yes state=present
  when: ansible_distribution == 'RedHat'

- name: install dependencies if needed
  yum: pkg={{ item }} state=latest
  with_items:
  - binutils
  - qt
  - gcc
  - make
  - patch
  - libgomp
  - glibc-headers
  - glibc-devel
  - kernel-headers
  - kernel-devel-{{ansible_kernel}}
  - dkms

- name: install Virtualbox package from Virtualbox Repository
  yum: state=present name={{ item }}
  with_items:
  - VirtualBox-5.1

- name: rebuild the kernel for VirtualBox drivers
  command: /usr/lib/virtualbox/vboxdrv.sh setup
